#############################################################################
# Generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#  Jul 29, 2025 08:58:06 PM PDT  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) white
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
set vTcl(project_theme) default



proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #d9d9d9 
    wm focusmodel $top passive
    wm geometry $top 600x450+1071+546
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 2727 1512
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Toplevel 0"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl::widgets::ttk::notebook::createCmd "$top.tNo54" \
        -width 582 -height 432 
    vTcl:DefineAlias "$top.tNo54" "NotebookBase" vTcl:WidgetProc "Toplevel1" 1
    frame "$top.tNo54.t0" \
        -background #d9d9d9 
    vTcl:DefineAlias "$top.tNo54.t0" "MainMenuTab" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo54 add $top.tNo54.t0 \
        -padding 0 -sticky nsew -state normal -text "Page 1" -compound left \
        -underline -1 
    set site_4_0  $top.tNo54.t0
    ttk::panedwindow "$site_4_0.tPa55" \
        -orient horizontal 
    vTcl:DefineAlias "$site_4_0.tPa55" "MainMenuPanedWindow" vTcl:WidgetProc "Toplevel1" 1
    ::vTcl::widgets::ttk::labelframe::createCmd "$site_4_0.tPa55.p1" \
        -text "Pane 1" -width 165 -height 200 
    vTcl:DefineAlias "$site_4_0.tPa55.p1" "MainMenuPanedWindow_p1" vTcl:WidgetProc "Toplevel1" 1
    set site_6_0 $site_4_0.tPa55.p1
    listbox "$site_6_0.lis47" \
        -background white -font "-family {Noto Sans Mono} -size 10" \
        -foreground #000000 -height 160 -selectbackground #d9d9d9 \
        -selectforeground black -width 134 
    $site_6_0.lis47 configure -font "TkFixedFont"
    $site_6_0.lis47 insert end text
    vTcl:DefineAlias "$site_6_0.lis47" "Listbox1" vTcl:WidgetProc "Toplevel1" 1
    place $site_6_0.lis47 \
        -in $site_6_0 -x 0 -y 0 -width 0 -relwidth 1 -height 0 -relheight 1 \
        -anchor nw -bordermode ignore 
    $site_4_0.tPa55 add $site_4_0.tPa55.p1 
    $site_4_0.tPa55 pane $site_4_0.tPa55.p1 -weight 0
    ::vTcl::widgets::ttk::labelframe::createCmd "$site_4_0.tPa55.p2" \
        -text "Pane 2" -width 125 -height 200 
    vTcl:DefineAlias "$site_4_0.tPa55.p2" "MainMenuPanedWindow_p2" vTcl:WidgetProc "Toplevel1" 1
    set site_6_1 $site_4_0.tPa55.p2
    button "$site_6_1.but49" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -font "-family {Noto Sans} -size 10" -foreground #000000 -text "Buy" 
    vTcl:DefineAlias "$site_6_1.but49" "BuyButton" vTcl:WidgetProc "Toplevel1" 1
    text "$site_6_1.tex55" \
        -background white -font "-family {Noto Sans} -size 10" \
        -foreground black -height 98 -selectbackground #d9d9d9 \
        -selectforeground black -width 76 -wrap word 
    $site_6_1.tex55 configure -font "TkTextFont"
    $site_6_1.tex55 insert end text
    vTcl:DefineAlias "$site_6_1.tex55" "TotalTextDisplay" vTcl:WidgetProc "Toplevel1" 1
    button "$site_6_1.but51" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -font "-family {Noto Sans} -size 10" -foreground #000000 -text "Sell" 
    vTcl:DefineAlias "$site_6_1.but51" "SellButton" vTcl:WidgetProc "Toplevel1" 1
    entry "$site_6_1.ent54" \
        -background white -font "-family {Noto Sans Mono} -size 10" \
        -foreground #000000 -selectbackground #d9d9d9 -selectforeground black \
        -width 76 
    vTcl:DefineAlias "$site_6_1.ent54" "AssetAmountEntry" vTcl:WidgetProc "Toplevel1" 1
    frame "$site_6_1.fra48" \
        -borderwidth 2 -relief groove -background #d9d9d9 -height 265 \
        -width 402 
    vTcl:DefineAlias "$site_6_1.fra48" "MPLPlaceholderFrame" vTcl:WidgetProc "Toplevel1" 1
    place $site_6_1.but49 \
        -in $site_6_1 -x 0 -relx 0.224 -y 0 -rely 0.729 -width 107 \
        -relwidth 0 -height 99 -relheight 0 -anchor nw -bordermode ignore 
    place $site_6_1.tex55 \
        -in $site_6_1 -x 0 -relx 0.771 -y 0 -rely 0.729 -width 0 \
        -relwidth 0.189 -height 0 -relheight 0.246 -anchor nw \
        -bordermode ignore 
    place $site_6_1.but51 \
        -in $site_6_1 -x 0 -relx 0.498 -y 0 -rely 0.729 -width 107 \
        -relwidth 0 -height 99 -relheight 0 -anchor nw -bordermode ignore 
    place $site_6_1.ent54 \
        -in $site_6_1 -x 0 -relx 0.025 -y 0 -rely 0.729 -width 76 -relwidth 0 \
        -height 99 -relheight 0 -anchor nw -bordermode ignore 
    place $site_6_1.fra48 \
        -in $site_6_1 -x 0 -y 0 -rely 0.05 -width 0 -relwidth 1 -height 0 \
        -relheight 0.666 -anchor nw -bordermode ignore 
    $site_4_0.tPa55 add $site_4_0.tPa55.p2 
    $site_4_0.tPa55 pane $site_4_0.tPa55.p2 -weight 0
$site_6_0 configure -width 165
    place $site_4_0.tPa55 \
        -in $site_4_0 -x 0 -relx 0.017 -y 0 -rely 0.025 -width 0 \
        -relwidth 0.957 -height 0 -relheight 0.95 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tNo54 \
        -in $top -x 0 -y 0 -width 0 -relwidth 1 -height 0 -relheight 1 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top2 {base} {
    global vTcl
    if {$base == ""} {
        set base .top2
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #d9d9d9 
    wm focusmodel $top passive
    wm geometry $top 600x450+1021+414
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 2727 1512
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Toplevel 1"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel2" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    ###################
    # SETTING GEOMETRY
    ###################

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}
set btop2 ""
if {$vTcl(borrow)} {
    set btop2 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop2 $vTcl(tops)] != -1} {
        set btop2 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop2
Window show .top2 $btop2
if {$vTcl(borrow)} {
    $btop2 configure -background plum
}

