name: Python App Build

on:
  push:
    branches:
      - main  # Change this to your default branch if needed
  pull_request:
    branches:
      - main  # Same here for PRs

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8, 3.9, 3.10]  # Add or remove versions as needed

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Make sure your dependencies are listed in this file

      - name: Compile the application
        run: |
          # Add your compilation or build steps here
          # For example, if using PyInstaller to create executables:
          pyinstaller --onefile your_script.py

      - name: Upload the build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: python-app-builds
          path: |
            dist/your_script  # Adjust according to the path where your executable is saved
